name: Merge Karabiner Docs
on:
  workflow_dispatch:

jobs:
  merge-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repo
        uses: actions/checkout@v4

      - name: Merge Markdown Files
        run: |
          cd sites/karabiner-elements/content/en/docs/

          find . -name "*.md" | sort | while read -r file; do
            echo -e "\n\n# Document Source: ${file#./}\n" >> /tmp/karabiner_docs_monolith.md
            cat "$file" >> /tmp/karabiner_docs_monolith.md
          done

          mv /tmp/karabiner_docs_monolith.md $GITHUB_WORKSPACE/

      - name: Upload Result to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: karabiner-final-docs
          path: ${{ github.workspace }}/karabiner_docs_monolith.md
